# Generated by Django 2.1.3 on 2022-06-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_name', models.CharField(max_length=200, null=True)),
                ('logfile', models.FileField(null=True, upload_to='logs')),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=200)),
                ('docfile', models.FileField(upload_to='trees/%Y/%m/%d')),
                ('tree_length', models.FloatField(default=0, null=True, verbose_name='Длина дерева')),
                ('tree_height', models.FloatField(default=0, null=True, verbose_name='Высота дерева')),
                ('tree_diameter', models.FloatField(default=0, null=True, verbose_name='Диаметр дерева')),
                ('tree_diameter_hyper', models.FloatField(default=0, null=True, verbose_name='Диаметр дерева Hyper')),
                ('tree_crown_height', models.FloatField(default=0, null=True, verbose_name='Высота кроны')),
                ('tree_crown_volume', models.FloatField(default=0, null=True, verbose_name='Объем кроны')),
                ('tree_crown_square', models.FloatField(default=0, null=True, verbose_name='Площадь кроны')),
                ('tree_img', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='images/', verbose_name='Изображение')),
                ('tree_plot', models.TextField(help_text='3d', null=True)),
                ('tree_eps', models.FloatField(default=0.35, null=True, verbose_name='eps')),
                ('tree_minpts', models.IntegerField(default=100, null=True, verbose_name='minpts')),
                ('tree_iter', models.IntegerField(default=1, null=True, verbose_name='iter')),
                ('tree_onnormalsz', models.BooleanField(default=1, verbose_name='onnormalsz')),
            ],
            options={
                'verbose_name': 'Дерево',
                'verbose_name_plural': 'Деревья',
            },
        ),
    ]
